apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb
  namespace: jenkins
  annotations:
    cloud.google.com/load-balancer-type: "External"
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080